name: Build and Deploy App to EKS

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  
on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4  
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ASSUMED }}
        aws-region: ${{ secrets.AWS_REGION }}
    
  # Get Org Secrets for Cluster
    - name: Retrieve EKS Cluster Secrets
      run: |
           echo "CLUSTER_NAME=${{ secrets.CLUSTER_NAME }}" >> $GITHUB_ENV
           echo "CLUSTER_ENDPOINT=${{ secrets.CLUSTER_ENDPOINT }}" >> $GITHUB_ENV
           echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
    
  # install aws cli
    - name: Install AWS CLI
      run: |
           sudo apt-get update
           sudo apt-get install awscli -y
           aws --version
     
  # Install kubectl
  
    - name: Install kubectl
      run: |
             curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
             sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
             kubectl version --client
           
  # get cluster ca data      
    - name: Get the cert data 
      run: >
         aws eks describe-cluster --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }} --query 'cluster.certificateAuthority.data' --output text | base64 --decode > ca.crt
    
  # update kubeconfig data  
    - name: Update kubeconfig for EKS with CA data
      run: >
        aws eks update-kubeconfig
        --name ${{ env.CLUSTER_NAME }}
        --endpoint-url ${{ env.CLUSTER_ENDPOINT }}
        --region ${{ env.AWS_REGION }} 
        --ca-bundle ./ca.crt
        --role-arn arn:aws:iam::209479268294:role/GithubOIDCRole
  
  # Setup Java
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
         distribution: 'temurin'
         java-version: '21'
    
  # Maven build
    - name: Build with Maven
      run: mvn clean package

  # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

  # Build Docker image with the tag in lowercase
    - name: Build Docker image
      run: |
        LOWERCASE_TAG=$(echo "ghcr.io/${{ github.repository_owner }}/crud:latest" | tr '[:upper:]' '[:lower:]')
        docker build -t $LOWERCASE_TAG .

  # Push Docker image to GitHub Container Registry
    - name: Push Docker image
      run: |
        LOWERCASE_TAG=$(echo "ghcr.io/${{ github.repository_owner }}/crud:latest" | tr '[:upper:]' '[:lower:]')
        docker push $LOWERCASE_TAG

  # Deploy the application to EKS using kubectl
    - name: App Deployment
      run:  kubectl apply -f k8s/deployment.yaml
      
  # Deploy the LoadBalancer
    - name: LB Deployment
      run:  kubectl apply -f k8s/service.yaml