name: Build and Deploy App to EKS
permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  
on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package

    # Initialize Terraform with the S3 backend configuration
    - name: Initialize Terraform
      run: terraform init -lock=false

    # Extract the EKS cluster name and endpoint from Terraform outputs
    - name: Extract Terraform outputs
      run: |
        CLUSTER_NAME=$(terraform output -raw eks_cluster_name)
        CLUSTER_ENDPOINT=$(terraform output -raw eks_cluster_endpoint)
        echo "CLUSTER_NAME=$CLUSTER_NAME" >> $GITHUB_ENV
        echo "CLUSTER_ENDPOINT=$CLUSTER_ENDPOINT" >> $GITHUB_ENV

    #Configure AWS parameters
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ASSUMED }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    
    # Configure the kubeconfig for EKS
    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --endpoint-url ${{ env.CLUSTER_ENDPOINT }} --region ${{ secrets.AWS_REGION }}

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    # Build Docker image with the tag in lowercase
    - name: Build Docker image
      run: |
        LOWERCASE_TAG=$(echo "ghcr.io/${{ github.repository_owner }}/crud:latest" | tr '[:upper:]' '[:lower:]')
        docker build -t $LOWERCASE_TAG .

    # Push Docker image to GitHub Container Registry
    - name: Push Docker image
      run: |
        LOWERCASE_TAG=$(echo "ghcr.io/${{ github.repository_owner }}/crud:latest" | tr '[:upper:]' '[:lower:]')
        docker push $LOWERCASE_TAG

    # Deploy the application to EKS using kubectl
    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml